name: CI Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: "sbonilla284"
      DOCKER_PASSWORD: "Admin123#"
          
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Construir la aplicación con Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Construir y etiquetar imagen Docker
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/app1:latest .
          docker tag ${{ env.DOCKER_USERNAME }}/app1:latest ${{ env.DOCKER_USERNAME }}/app1:${{ github.run_number }}

      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/app1:latest
          docker push ${{ env.DOCKER_USERNAME }}/app1:${{ github.run_number }}
          
  update-helm-chart:
    runs-on: ubuntu-latest
    needs: build  # Espera a que termine el job `build`
  
    steps:
      - name: Clonar el repo del Helm Chart
        uses: actions/checkout@v3
        with:
          repository: SantiagoBonillaGuevara/app1-chart
          token: ${{ secrets.HELM_REPO_TOKEN }}
  
      - name: Modificar el `values.yaml` con la nueva imagen
        run: |
          sed -i "s/tag: \"[0-9]*\"/tag: \"${{ github.run_number }}\"/" values.yaml
  
      - name: Hacer commit y push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push origin main
