name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: "sbonilla284"
      DOCKER_PASSWORD: "Admin123#"
          
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Construir la aplicación con Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Construir y etiquetar imagen Docker
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/app1:latest .
          docker tag ${{ env.DOCKER_USERNAME }}/app1:latest ${{ env.DOCKER_USERNAME }}/app1:${{ github.run_number }}

      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/app1:latest
          docker push ${{ env.DOCKER_USERNAME }}/app1:${{ github.run_number }}

